spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/miniproj
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: xyz@gmail.com
    password: xyz@321
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    